language: go
go:
        - 1.4
env:
        - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
        - go get github.com/mitchellh/gox
        - gox -build-toolchain
after_success:
        - gox -output "dist/{.OS}_{.Arch}_{.Dir}
