language: go
go:
        - 1.4
env:
        - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
        - go get github.com/mitchellh/gox
        - go get github.com/mgutz/ansi
        - go get github.com/howeyc/gopass
        - go get github.com/PuerkitoBio/goquery
        - go get github.com/mitchellh/gox

        - gox -build-toolchain
script: make
deploy:
        provider: releases
        api_key: 
                secure: klyHgjzeWE96Dj89Y3Ft+tHkBfIaSXTTtDP/qRtMSwcQsBPwBjdXvjac/1+9mSmqJ+vDBd0DjMULbNzNgGyogSd8gGDqKBpjraxSKYRDFcBVItRGenOmQzIpvuryRkhGPBGLlqUpaRbd98ZNVQ2OJlhwwdWlfRo55z+jVhfxlX8=
        file: swipe-go-win32.zip
        skip_cleanup: true
        all_branches: true
        on:
                tags: true
after_success:
        - gox -output "dist/{.OS}_{.Arch}_{.Dir}
